version: '3'
services: 
    angular:
        container_name: frontend
        build: frontend
        #only if you are serving the compiled angular files or static content using nginx
         #volumes:
           # - ./frontend/dist/mean-course:/usr/share/nginx/html
        ports: 
            - '8080:80'

    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '2720:27017'
     

    express:
        container_name: backend
        restart: always
        build: backend
        environment:
            - BACKEND_SERVER=secret_this_should_be_super_long
        ports: 
            - '3000:3000'
        volumes:
            - ./backend:/src/app
            - /src/app/node_modules
        links:
            - mongo


     


  
           
